version: '3.2'
services:
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./down:/usr/share/nginx/html/download
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8888:8888"
    restart: always
